AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    AssociationTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            PrimaryKey:
                Name: uuid
                Type: String
            TableName: Association

    WebsocketApi:
        Type: AWS::ApiGatewayV2::Api
        Properties:
            Name: messages-api
            ProtocolType: WEBSOCKET
            RouteSelectionExpression: '$request.body.action'

    ConnectRoute:
        Type: AWS::ApiGatewayV2::Route
        Properties:
            RouteKey: $connect
            ApiId: !Ref WebsocketApi
            AuthorizationType: NONE
            OperationName: ConnectRoute
            RouteResponseSelectionExpression: $default
            Target: !Join
                - /
                - - integrations
                  - !Ref ConnectIntegration
    ConnectFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: .
            Handler: src/lambda-handlers/onConnect.handler
            MemorySize: 256
            Runtime: nodejs12.x
    ConnectIntegration:
        Type: AWS::ApiGatewayV2::Integration
        Properties:
            ApiId: !Ref WebsocketApi
            IntegrationType: AWS
            IntegrationUri:
                Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectFunction.Arn}/invocations
    ConnectRouteResponse:
        Type: 'AWS::ApiGatewayV2::RouteResponse'
        Properties:
            RouteId: !Ref ConnectRoute
            ApiId: !Ref WebsocketApi
            RouteResponseKey: $default
    ConnectIntegrationResponse:
        Type: 'AWS::ApiGatewayV2::IntegrationResponse'
        Properties:
            IntegrationId: !Ref ConnectIntegration
            IntegrationResponseKey: $default
            TemplateSelectionExpression: \$default
            ResponseTemplates:
                '$default': "$input.json('$')"
            ApiId: !Ref WebsocketApi

    ProcessRoute:
        Type: AWS::ApiGatewayV2::Route
        Properties:
            RouteKey: $default
            ApiId: !Ref WebsocketApi
            AuthorizationType: NONE
            OperationName: ProcessRoute
            RouteResponseSelectionExpression: $default
            Target: !Join
                - /
                - - integrations
                  - !Ref ProcessIntegration
    ProcessFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: .
            Handler: src/lambda-handlers/onProcess.handler
            MemorySize: 256
            Runtime: nodejs12.x
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref AssociationTable
            Environment:
                Variables:
                    TABLE_NAME: !Ref AssociationTable
                    MESSAGES_API_HOST: api.nexmo.com
                    INBOUND_STAGE: Prod
                    INBOUND_API_ID: !Ref InboundCallbackApi

    ProcessIntegration:
        Type: AWS::ApiGatewayV2::Integration
        Properties:
            ApiId: !Ref WebsocketApi
            IntegrationType: AWS
            TemplateSelectionExpression: \$default
            RequestTemplates:
                '$default': '{"context":{"connectionId":"$context.connectionId"},"input":$input.json(''$'')}'
            IntegrationUri:
                Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProcessFunction.Arn}/invocations
    ProcessRouteResponse:
        Type: 'AWS::ApiGatewayV2::RouteResponse'
        Properties:
            RouteId: !Ref ProcessRoute
            ApiId: !Ref WebsocketApi
            RouteResponseKey: $default
    ProcessIntegrationResponse:
        Type: 'AWS::ApiGatewayV2::IntegrationResponse'
        Properties:
            IntegrationId: !Ref ProcessIntegration
            IntegrationResponseKey: $default
            TemplateSelectionExpression: \$default
            ResponseTemplates:
                '$default': "$input.json('$')"
            ApiId: !Ref WebsocketApi

    DisconnectRoute:
        Type: AWS::ApiGatewayV2::Route
        Properties:
            RouteKey: $disconnect
            ApiId: !Ref WebsocketApi
            AuthorizationType: NONE
            OperationName: DisconnectRoute
            Target: !Join
                - /
                - - integrations
                  - !Ref DisconnectIntegration
    DisconnectIntegration:
        Type: AWS::ApiGatewayV2::Integration
        Properties:
            ApiId: !Ref WebsocketApi
            IntegrationType: MOCK

    InboundCallbackApi:
        Type: AWS::Serverless::Api
        Properties:
            Name: messages-api-callback
            StageName: Prod

    InboundCallbackFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: .
            Handler: src/lambda-handlers/processCallback.handler
            Runtime: nodejs12.x
            MemorySize: 256
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref AssociationTable
                - Version: '2012-10-17'
                  Statement:
                      - Effect: Allow
                        Action:
                            - execute-api:ManageConnections
                        Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*'
            Environment:
                Variables:
                    TABLE_NAME: !Ref AssociationTable
                    WEBSOCKET_API_ID: !Ref WebsocketApi
                    WEBSOCKET_STAGE: Prod
            Events:
                HttpPost:
                    Type: Api
                    Properties:
                        Path: '/callback'
                        Method: post
                        RestApiId: !Ref InboundCallbackApi

    Deployment:
        Type: AWS::ApiGatewayV2::Deployment
        DependsOn:
            - ProcessRoute
            - ProcessRouteResponse
            - ProcessIntegrationResponse
            - ConnectRoute
            - ConnectRouteResponse
            - ConnectIntegrationResponse
        Properties:
            ApiId: !Ref WebsocketApi
    Stage:
        Type: AWS::ApiGatewayV2::Stage
        Properties:
            StageName: Prod
            DeploymentId: !Ref Deployment
            ApiId: !Ref WebsocketApi
            DefaultRouteSettings:
                LoggingLevel: INFO
                DetailedMetricsEnabled: true
                DataTraceEnabled: true

    ConnectPermission:
        Type: AWS::Lambda::Permission
        DependsOn:
            - WebsocketApi
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref ConnectFunction
            Principal: apigateway.amazonaws.com
    ProcessPermission:
        Type: AWS::Lambda::Permission
        DependsOn:
            - WebsocketApi
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref ProcessFunction
            Principal: apigateway.amazonaws.com

Outputs:
    WebSocketURI:
        Description: 'The WSS Protocol URI to connect to'
        Value:
            !Join [
                '',
                [
                    'wss://',
                    !Ref WebsocketApi,
                    '.execute-api.',
                    !Ref 'AWS::Region',
                    '.amazonaws.com/',
                    !Ref 'Stage',
                ],
            ]
